/* eslint-disable sort-keys -- disabled */
/* eslint-disable node/no-unpublished-import -- disabled */
import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography";
import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/modules/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/common/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/common/components/*.{js,ts,jsx,tsx,mdx}",
    ],
    plugins: [typography(), forms()],
    theme: {
        extend: {
            backgroundImage: {
                "gradient-conic":
                    "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
                "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
            },
            fontSize: {
                calcsm: "calc(0.5rem + 1vw)",
                calcmd: "calc(2rem + 5vw)",
                calclg: "calc(3.5rem + 20vw)",
                xxs: "0.5rem",
            },
            gap: {
                "-1": "-0.25rem",
                "-2": "-0.5rem",
                "-3": "-0.75rem",
            },
            left: {
                "3.5/4": "87.5%",
                "3.75/4": "93.75%",
            },
            minHeight: {
                "0.5": "0.125rem",
                "1": "0.25em",
                "1.5": "0.375rem",
                "2": "0.5rem",
                "2.5": "0.625rem",
                "3": "0.75rem",
                "3.5": "0.875rem",
                "4": "1rem",
                "5": "1.25rem",
                "6": "1.5rem",
                "7": "1.75rem",
                "8": "2rem",
                "9": "2.25rem",
                "10": "2.5rem",
                "11": "2.75rem",
                "12": "3rem",
                "14": "3.5rem",
                "16": "4rem",
                "18": "4.5rem",
                "20": "5rem",
                "22": "5.5rem",
                "24": "6rem",
                "26": "6.5rem",
                "28": "7rem",
                "30": "7.5rem",
                "35": "8.25rem",
                "40": "9rem",
                "45": "9.75rem",
                "50": "10.5rem",
                "60": "12rem",
                "70": "13.5rem",
                "80": "15rem",
                "90": "16.5rem",
                "100": "18rem",
                "10vh": "10vh",
                "20vh": "20vh",
                "30vh": "30vh",
                "40vh": "40vh",
                "50vh": "50vh",
                "55vh": "55vh",
                "60vh": "60vh",
                "65vh": "65vh",
                "70vh": "70vh",
                "80vh": "80vh",
                "90vh": "90vh",
                "100vh": "100vh",
            },
            maxHeight: {
                "5/6": "83.33333%",
            },
            maxWidth: {
                "1vw": "1vw",
                "2vw": "2vw",
                "3vw": "3vw",
                "4vw": "4vw",
                "5vw": "5vw",
                "6vw": "6vw",
                "7vw": "7vw",
                "8vw": "8vw",
                "9vw": "9vw",
                "10vw": "10vw",
                "15vw": "15vw",
                "20vw": "20vw",
                "25vw": "25vw",
                "50vw": "50vw",
                "75vw": "75vw",
                "100vw": "100vw",
            },
            minWidth: {
                "1vw": "1vw",
                "2vw": "2vw",
                "3vw": "3vw",
                "4vw": "4vw",
                "5vw": "5vw",
                "6vw": "6vw",
                "7vw": "7vw",
                "8vw": "8vw",
                "9vw": "9vw",
                "10vw": "10vw",
                "15vw": "15vw",
                "20vw": "20vw",
                "25vw": "25vw",
                "50vw": "50vw",
                "75vw": "75vw",
                "100vw": "100vw",
            },
            right: {
                ".5": ".125rem",
            },
            top: {
                "3/4": "75%",
                "8/9": "90%",
            },
            zIndex: {
                max: "9999",
            },
        },
        flexBasis: {
            "1/4": "25%",
            "2/4": "50%",
            "3/4": "75%",
            "4/4": "100%",
        },
    },
};
export default config;
