/* eslint-disable node/no-unpublished-import -- disabled */
/* eslint-disable new-cap -- disabled */
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import "tailwindcss/tailwind.css";

// Import "../assets/css/main.css";
import type { Metadata } from "next";
import React, { type PropsWithChildren } from "react";
import { ToastContainer } from "react-toastify";

import QueryProvider from "@/query";

const metadata: Metadata = {
    description: "Generated by create next app",
};

/**
 *
 * @param props - The properties of the root layout component
 * @param props.children - The children of the root layout
 * @returns The root layout component
 */
const RootLayout = ({ children }: PropsWithChildren): JSX.Element => (
    <html lang="en">
        <head>
            <link
                crossOrigin="anonymous"
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
                integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
                rel="stylesheet"
            />
            <link
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
                rel="stylesheet"
            />
        </head>
        <body className="relative">
            <QueryProvider>{children}</QueryProvider>
            <ToastContainer
                autoClose={5000}
                closeOnClick
                draggable
                hideProgressBar={false}
                newestOnTop={false}
                pauseOnFocusLoss={false}
                pauseOnHover
                position="top-left"
                rtl={false}
                theme="light"
            />
        </body>
    </html>
);

export { RootLayout as default, metadata };
