/* eslint-disable node/no-unpublished-import -- disabled */
/* eslint-disable new-cap -- disabled */
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import "tailwindcss/tailwind.css";
// import "../assets/css/main.css";

import type { Metadata } from "next";
import {
    Bebas_Neue,
    JetBrains_Mono,
    Poppins,
    Quicksand,
} from "next/font/google";
import React, { type PropsWithChildren } from "react";
import { ToastContainer } from "react-toastify";

// import { elementIds } from "@/common/constants/ids";
// import { LoadingProvider } from "@/providers/loading";
import QueryProvider from "@/query";
// import { SoundProvider } from "@/providers/sound";

const jetbrains = JetBrains_Mono({
    subsets: ["latin"],
    variable: "--jetbrains",
});
const quickSand = Quicksand({ subsets: ["latin"], variable: "--quicksand" });

const bebasNeue = Bebas_Neue({
    subsets: ["latin"],
    variable: "--bebas_neue",
    weight: "400",
});

const poppins = Poppins({
    subsets: ["latin"],
    variable: "--poppins",
    weight: "400",
});

const metadata: Metadata = {
    description: "Generated by create next app",
    title: "Quantum Task Hub",
};

/**
 *
 * @param props - The properties of the root layout component
 * @param props.children - The children of the root layout
 * @returns The root layout component
 */
const RootLayout = ({ children }: PropsWithChildren): JSX.Element => (
    <html lang="en">
        <head>
            <link
                crossOrigin="anonymous"
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
                integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
                rel="stylesheet"
            />
            <link
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
                rel="stylesheet"
            />
        </head>
        <body
            className={`${jetbrains.variable} ${quickSand.variable} ${bebasNeue.variable} ${jetbrains.className} ${poppins.variable} relative`}
            // id={elementIds.BODY}
        >
            <QueryProvider>{children}</QueryProvider>
            <ToastContainer
                autoClose={5000}
                closeOnClick
                draggable
                hideProgressBar={false}
                newestOnTop={false}
                pauseOnFocusLoss={false}
                pauseOnHover
                position="top-left"
                rtl={false}
                theme="light"
            />
            {/* <SoundProvider />
            <React.Suspense fallback={<span className="hidden" />}>
                <LoadingProvider />
            </React.Suspense> */}
        </body>
    </html>
);

export { RootLayout as default, metadata };
